version: '3.9'

services:

    cc-postgres:
        container_name: cc-postgres
        image: postgres
        restart: always
        networks:
            - cc-postgres-net
        volumes:
            - cc-postgres-data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234

    cc-django:
        container_name: cc-django
        build:
            context: .
        image: cc/django
        depends_on:
            - cc-postgres
        networks:
            - cc-postgres-net
            - cc-django-net
        healthcheck:
            test: curl --fail http://0.0.0.0:8800/healthcheck/ || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            - DB_HOST=cc-postgres

    cc-nginx:
        container_name: cc-nginx
        image: nginx
        depends_on:
            - cc-django
        ports:
            - 8800:80
        networks:
            - cc-django-net
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/app/cloud_coupon/static/

networks:
    cc-postgres-net:
        driver: bridge
    cc-django-net:
        driver: bridge

volumes:
    cc-postgres-data:
