# Generated by Django 4.2 on 2023-06-20 19:49

import apps.couponing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponing', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='server',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'USA'), (1, 'EU'), (2, 'UAE')], null=True, verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=apps.couponing.models.generate_unique_code, editable=False, max_length=6, unique=True, verbose_name='Code'),
        ),
    ]
