# Generated by Django 4.2 on 2023-06-20 19:54

import apps.couponing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponing', '0003_coupon_server_coupon_value_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=apps.couponing.models.generate_unique_code, max_length=6, unique=True, verbose_name='Code'),
        ),
    ]
