# Generated by Django 4.2 on 2023-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponing', '0004_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Redeemable')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
