# Generated by Django 4.2 on 2023-06-22 09:51

import apps.coupon.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(blank=True, default=apps.coupon.utils.generate_unique_code, max_length=6, unique=True, verbose_name='Code')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Value')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count')),
                ('type', models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Discount')], verbose_name='Type')),
                ('server', models.SmallIntegerField(blank=True, choices=[(0, 'USA'), (1, 'EU'), (2, 'UAE')], null=True, verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupon.coupon')),
            ],
            options={
                'verbose_name': 'User Coupon',
                'verbose_name_plural': 'User Coupons',
            },
        ),
    ]
