# Generated by Django 4.2 on 2023-06-21 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count'),
        ),
    ]
