# Generated by Django 4.2 on 2023-06-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='is_enabled',
        ),
    ]
